service:
  name: twitter-admin

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accounts
        AttributeDefinitions:
          - AttributeName: account_type
            AttributeType: S
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: account_type
            KeyType: HASH
          - AttributeName: uid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8010
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
      migrate: true
  dotenv:
    path: ./.env
    include:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - LINE_BOT_CHANNEL_ACCESSTOKEN
      - LINE_BOT_CHANNEL_ID
      - LINE_BOT_CHANNEL_SECRET
      - LINE_AUTH_CHANNEL_ID
      - LINE_AUTH_CHANNEL_SECRET
      - LINE_NOTIFY_CLIENT_ID
      - LINE_NOTIFY_CLIENT_SECRET
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - DISCORD_CLIENT_BOT_ACCESSTOKEN
      - FACEBOOK_APP_ID
      - FACEBOOK_APP_SECRET
      - region
      - endpoint

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: src/app.handler
    memorySize: 128
    timeout: 900
    events:
      - http: ANY /
      - http: ANY /{proxy+}